//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> MainCategoryID { get; set; }
        public Nullable<int> MediumCategoryID { get; set; }
        public Nullable<int> SmallCategoryID { get; set; }
        public Nullable<int> ClickCount { get; set; }
        public Nullable<int> ReplyCount { get; set; }
        public string Url { get; set; }
        public string Favorite { get; set; }
        public string Site { get; set; }
        public string ChannelType { get; set; }
        public string Content { get; set; }
        public string ScreenshotsPath { get; set; }
        public Nullable<int> Rating { get; set; }
        public string JudgeContent { get; set; }
        public string SuggestContent { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string RelateQuestion { get; set; }
    }
}
