//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataServiceCategory
    {
        public int ID { get; set; }
        public Nullable<int> SettingCategoryID { get; set; }
        public string CategoryName { get; set; }
        public string GroupName { get; set; }
        public string CategoryItem { get; set; }
    }
}
