//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public string ReportName { get; set; }
        public string Company { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ReportType { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string Day { get; set; }
        public string CurrentNumber { get; set; }
        public string TotalNumber { get; set; }
        public string StrText { get; set; }
        public Nullable<int> News_number { get; set; }
        public Nullable<int> Hudong_number { get; set; }
        public Nullable<int> Mingan_number { get; set; }
        public string Info_total_pic { get; set; }
        public string PriorityArticles { get; set; }
        public string DistributeSummary { get; set; }
        public string Distribute_Pic { get; set; }
        public string DistributeContent { get; set; }
        public string NextWeekWarning_Pic { get; set; }
        public string NextWeekMinganValue { get; set; }
        public Nullable<int> NextWeekSustainNumber { get; set; }
        public string AttentionQuestions { get; set; }
        public string ReportsExcerpt { get; set; }
        public string Week_Pic { get; set; }
        public Nullable<int> LowExponent { get; set; }
        public Nullable<int> HeightExponent { get; set; }
        public Nullable<int> AvgExponent { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> StartDay { get; set; }
        public Nullable<int> LowNumber { get; set; }
        public Nullable<int> EndMonth { get; set; }
        public Nullable<int> EndDay { get; set; }
        public Nullable<int> HeightNumber { get; set; }
        public string Tend { get; set; }
        public string Attention_Picture { get; set; }
        public Nullable<int> Total_AttentionNumber { get; set; }
        public Nullable<int> Mobile_AttentNumber { get; set; }
        public string Total_FloatingType { get; set; }
        public string Total_AttentionPercent { get; set; }
        public string Mobile_FloatingType { get; set; }
        public string Mobile_AttentionPercent { get; set; }
        public string AttentionCities { get; set; }
        public string Police_pic { get; set; }
        public string Topic1Guide { get; set; }
        public string Topic1_pic { get; set; }
        public string Topic2Guide { get; set; }
        public string Topic2_pic { get; set; }
        public string Topic3Guide { get; set; }
        public string Topic3_pic { get; set; }
        public string Investment_pic { get; set; }
        public string Technology_pic { get; set; }
        public string Reference_pic { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> Paper_Number { get; set; }
        public string Topic1Title { get; set; }
        public string Topic2Title { get; set; }
        public string Topic3Title { get; set; }
        public string Area { get; set; }
        public string Subsidiary { get; set; }
    }
}
