//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportContext : DbContext
    {
        public ReportContext()
            : base("name=ReportContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportNumber> ReportNumbers { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<ReferenceReport> ReferenceReports { get; set; }
        public virtual DbSet<CustomerCategory> CustomerCategories { get; set; }
        public virtual DbSet<SendPort> SendPorts { get; set; }
        public virtual DbSet<Subsidiary> Subsidiaries { get; set; }
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<ChannelContent> ChannelContents { get; set; }
        public virtual DbSet<QuestionCategory> QuestionCategories { get; set; }
    }
}
