//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmallCategory
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> MainCategoryID { get; set; }
        public Nullable<int> MediumCategoryID { get; set; }
        public string CategoryDescription { get; set; }
    }
}
